### ISSUE TITLE
sothing wrong 

### ISSUE THREAD

**Issue by joykaiyo** [sammachin/EchoRTC#1]
![QQ截图20190805164147](https://user-images.githubusercontent.com/25899397/62450978-f0d9cf00-b79f-11e9-9d39-791e6ccdf46f.jpg)

**Comment by cjk7713** [comment]
TypeError: Cannot read property 'send' of undefined
    at /web/jax/EchoRTC/local_server.js:17:10
    at Layer.handle [as handle_request] (/web/jax/EchoRTC/node_modules/express/lib/router/layer.js:95:5)
    at next (/web/jax/EchoRTC/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/web/jax/EchoRTC/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/web/jax/EchoRTC/node_modules/express/lib/router/layer.js:95:5)
    at /web/jax/EchoRTC/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/web/jax/EchoRTC/node_modules/express/lib/router/index.js:335:12)
    at next (/web/jax/EchoRTC/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/web/jax/EchoRTC/node_modules/serve-static/index.js:75:16)
    at Layer.handle [as handle_request] (/web/jax/EchoRTC/node_modules/express/lib/router/layer.js:95:5)

**Comment by cjk7713** [comment]
Where did this variable come in
